wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718049987.165862
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 23
      4: 3.9.12
      5: 0.15.10
      8:
      - 4
      - 5
